# =============================================================================
# Valid Model Manifest
# =============================================================================
# This manifest represents a properly configured model deployment that passes
# all governance policies.
#
# Validate: conftest test examples/valid/model-manifest.yaml -p src/policies/
# =============================================================================

apiVersion: mlifecycle.io/v1
kind: ModelDeployment
metadata:
  name: fraud-detector
  namespace: ml-inference
  labels:
    app: fraud-detector
    version: v2.1.0
    team: ml-platform
    environment: production

spec:
  # -------------------------------------------------------------------------
  # Model Configuration
  # -------------------------------------------------------------------------
  model:
    name: fraud-detector
    version: "2.1.0"
    uri: s3://approved-data-bucket/models/fraud-detector/v2.1.0
    framework: pytorch
    experiment_id: exp-fraud-2025-001
    description: "Real-time fraud detection for payment transactions"

  # -------------------------------------------------------------------------
  # Performance Metrics (Required)
  # -------------------------------------------------------------------------
  metrics:
    accuracy: 0.94
    precision: 0.91
    recall: 0.89
    f1_score: 0.90
    auc_roc: 0.96
    # Training metadata
    training_date: "2025-01-01"
    training_duration_hours: 4.5
    training_samples: 1500000

  # -------------------------------------------------------------------------
  # Fairness / Bias Metrics (Required)
  # -------------------------------------------------------------------------
  fairness:
    demographic_parity: 0.02
    equalized_odds: 0.03
    evaluation_date: "2025-01-02"
    protected_attributes:
      - gender
      - age_group
      - geographic_region

  # -------------------------------------------------------------------------
  # Drift Monitoring
  # -------------------------------------------------------------------------
  drift:
    score: 0.05
    reference_dataset: "2024-12-baseline"
    monitored_features:
      - transaction_amount
      - merchant_category
      - hour_of_day
      - day_of_week
    last_evaluated: "2025-01-02"

  # -------------------------------------------------------------------------
  # Dependencies (Must be from approved list)
  # -------------------------------------------------------------------------
  dependencies:
    - torch>=2.0.0
    - torchvision>=0.15.0
    - numpy>=1.24.0
    - pandas>=2.0.0
    - scikit-learn>=1.3.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0

  # -------------------------------------------------------------------------
  # Data Sources (Must be approved)
  # -------------------------------------------------------------------------
  data_sources:
    - source: transactions-prod
      version: "2024-12"
      approved: true
      description: "Production transaction data"
    - source: s3://approved-data-bucket/features/
      version: "v3"
      approved: true
      description: "Feature store snapshot"

  # -------------------------------------------------------------------------
  # Inference Configuration
  # -------------------------------------------------------------------------
  inference:
    replicas: 2

    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"

    autoscaling:
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilization: 70
      targetMemoryUtilization: 80

    # Health check configuration
    healthCheck:
      path: /health
      port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10

    # Readiness check configuration
    readinessCheck:
      path: /ready
      port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5

  # -------------------------------------------------------------------------
  # Monitoring (Required for production)
  # -------------------------------------------------------------------------
  monitoring:
    enabled: true
    drift_detection:
      enabled: true
      schedule: "0 */6 * * *"  # Every 6 hours
      threshold: 0.3
    alerting:
      enabled: true
      channels:
        - slack
        - pagerduty
      rules:
        - name: high_error_rate
          condition: "error_rate > 0.05"
          severity: critical
        - name: high_latency
          condition: "latency_p99 > 500ms"
          severity: warning

  # -------------------------------------------------------------------------
  # Explainability (Recommended)
  # -------------------------------------------------------------------------
  explainability:
    method: shap
    enabled: true
    feature_importance:
      - transaction_amount
      - merchant_category
      - hour_of_day

  # -------------------------------------------------------------------------
  # Observability
  # -------------------------------------------------------------------------
  observability:
    metrics:
      enabled: true
      port: 8080
      path: /metrics
    logging:
      level: INFO
      format: json
    tracing:
      enabled: true
      samplingRate: 0.1

  # -------------------------------------------------------------------------
  # Rollback Configuration
  # -------------------------------------------------------------------------
  rollback:
    enabled: true
    previousVersion: "2.0.0"
    triggers:
      - type: error_rate
        threshold: 0.05
        window: 5m
      - type: latency_p99
        threshold: 500ms
        window: 5m
